OPENAI_BASE_URL = "http://localhost:11434/v1"
OPENAI_API_KEY = "SOME-API-KEY"

MODEL_OCR = "qwen2.5vl:32b-q8_0"
MODEL_SEGMENTATION = "qwen2.5vl:32b-q8_0"

TEMPERATURE_OCR = 0
TEMPERATURE_SEGMENTATION = 0

DIRECTORY_SOURCE = "source"
DIRECTORY_OUTPUT = "texts"
