[package]
name = "srednjeveski-arhivi"
description = "Program for digitizing and searching medieval records"
authors = ["Vida Mlinar", "Filip Štamcar"]
repository = "https://github.com/Vida26365/SrednjeveskiArhivi"
license = "MIT"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1.0.0"
dioxus = { version = "0.6.3", features = ["desktop", "router"] }
directories = "6.0.0"
sea-orm = { version = "1.1.8", features = ["sqlx-sqlite", "runtime-tokio", "macros"] }
tokio = { version = "1.44.2", features = ["full"] }
uuid = "1.16.0"

[build-dependencies]
cfg_aliases = "0.2.1"

[profile.release]
codegen-units = 1
strip = true
lto = true

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
